import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';
import '@storybook/addon-knobs/register';
import '@storybook/addon-a11y/manager';
import '@storybook/addon-a11y/register';
import '@storybook/addon-storysource/register';
import '@storybook/addon-viewport';
import '@storybook/addon-docs/manager';
import '@storybook/addon-docs/manager';